#HWK1 BY ARMENOUSH ASLANIAN-PERSICO
#Q1
SELECT 
ORIGIN, DEST, DISTANCE 
FROM flights 
ORDER BY distance DESC 
LIMIT 1;
#Q2
SELECT 
ENGINES, MANUFACTURER, MODEL, ENGINE, MAX(SEATS) 
FROM PLANES 
GROUP BY ENGINES 
ORDER BY ENGINES DESC;
#Q3
SELECT 
COUNT(FLIGHT) 
FROM FLIGHTS;
#Q4
SELECT CARRIER, COUNT(FLIGHT) 
FROM FLIGHTS 
GROUP BY CARRIER 
ORDER BY CARRIER;
#Q5
SELECT CARRIER, COUNT(FLIGHT) 
FROM FLIGHTS 
GROUP BY CARRIER 
ORDER BY COUNT(FLIGHT) DESC;
#Q6
SELECT CARRIER, COUNT(FLIGHT) 
FROM FLIGHTS 
GROUP BY CARRIER 
ORDER BY COUNT(FLIGHT) DESC 
LIMIT 5;
#Q7
SELECT CARRIER, COUNT(FLIGHT) AS 'COUNT OF FLIGHTS', ROUND(AVG(DISTANCE)) AS 'AVERAGE ROUNDED DISTANCE IN MILES' 
FROM FLIGHTS 
WHERE DISTANCE>=1000 
GROUP BY CARRIER 
ORDER BY COUNT(FLIGHT) DESC 
LIMIT 5;
#Q8
#SHOW AIRPORTS BY AVERAGE DEPARTURE DELAY, ORDERED BY AVERAGE DEPARTURE DELAY IN DESCENDING ORDER
SELECT ORIGIN, ROUND(AVG(DEP_DELAY)) AS 'AVERAGE ROUNDED DEPARTURE DELAY IN MINUTES' 
FROM FLIGHTS 
GROUP BY ORIGIN 
ORDER BY AVG(DEP_DELAY) DESC;